sad.c: Refactor function to conform with GNU89 standard
When compiling with --std=gnu89 cflag, there is following compilation error:
sad.c: In function ‘sad_config_security_association_key’:
sad.c:656:17: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
  656 |                 for (int i = 0; i < key_len; i += 2) {
      |                 ^~~
sad.c:656:17: note: use option ‘-std=c99’, ‘-std=gnu99’, ‘-std=c11’ or ‘-std=gnu11’ to compile your code

Usage of gnu89 (c89 does not work, since Linuxptp uses some gnu extensions) is
almost never default in current compilators, thus this change have appeared.
But whole codebase conforms with gnu89, thus change conflicting change to
work with it.

Signed-off-by: Jakub Raczynski <myszsoda@gmail.com>
Reviewed-by: Jacob Keller <jacob.e.keller@intel.com>